"""
Review Agent — Analyses a CDK diff/plan and posts a structured review to a GitHub PR.

Triggered when a CDK plan completes in GitHub Actions.
Returns PASS / WARN / BLOCK verdict with per-finding details.

Security constraints:
- READ-ONLY AWS access
- Cannot call CDK deploy or any mutating AWS API
- All I/O logged to audit S3 bucket
"""

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import anthropic
import structlog

log = structlog.get_logger(__name__)

client = anthropic.Anthropic()

SYSTEM_PROMPT = Path(__file__).parent / "prompts" / "review_plan.md"
MODEL = "claude-sonnet-4-6"


@dataclass
class Finding:
    severity: Literal["INFO", "WARN", "BLOCK"]
    rule: str
    resource: str
    detail: str


@dataclass
class ReviewResult:
    verdict: Literal["PASS", "WARN", "BLOCK"]
    summary: str
    findings: list[Finding]
    cost_delta_usd_monthly: float | None
    recommended_action: str

    def to_pr_comment(self) -> str:
        """Format review result as a GitHub PR comment in Markdown."""
        icon = {"PASS": "✅", "WARN": "⚠️", "BLOCK": "🚫"}[self.verdict]
        lines = [
            f"## {icon} CDK Plan Review — {self.verdict}",
            f"",
            f"**Summary:** {self.summary}",
            f"",
        ]

        if self.cost_delta_usd_monthly is not None:
            lines += [
                f"**Estimated monthly cost delta:** ${self.cost_delta_usd_monthly:,.2f}",
                f"",
            ]

        if self.findings:
            lines += ["### Findings", ""]
            for f in self.findings:
                icon_f = {"INFO": "ℹ️", "WARN": "⚠️", "BLOCK": "🚫"}[f.severity]
                lines.append(f"{icon_f} **[{f.severity}]** `{f.rule}` — `{f.resource}`")
                lines.append(f"   > {f.detail}")
                lines.append("")

        lines += [
            "### Recommended Action",
            self.recommended_action,
            "",
            "---",
            "*Review generated by IDP Review Agent. Human approval is still required.*",
        ]
        return "\n".join(lines)


def review_cdk_plan(
    cdk_diff_output: str,
    cdk_synth_path: str | None = None,
    job_id: str = "unknown",
) -> ReviewResult:
    """
    Analyse a CDK diff output and return a structured review.

    Args:
        cdk_diff_output: The stdout of `cdk diff` command.
        cdk_synth_path: Optional path to synthesised CloudFormation template.
        job_id: Correlation ID for audit logging.

    Returns:
        ReviewResult with verdict and structured findings.
    """
    system_prompt = SYSTEM_PROMPT.read_text()

    synth_context = ""
    if cdk_synth_path:
        try:
            synth_context = f"\n\nSYNTHESISED TEMPLATE:\n{Path(cdk_synth_path).read_text()[:8000]}"
        except OSError:
            pass

    user_message = f"""Review this CDK plan output for security, compliance, and cost issues.

Return ONLY valid JSON matching the schema:
{{
  "verdict": "PASS" | "WARN" | "BLOCK",
  "summary": "one-line summary",
  "findings": [
    {{"severity": "INFO"|"WARN"|"BLOCK", "rule": "rule-id", "resource": "resource-id", "detail": "explanation"}}
  ],
  "cost_delta_usd_monthly": <float or null>,
  "recommended_action": "what the reviewer should do"
}}

RULES TO CHECK:
- BLOCK: Any IAM role without IRSA trust policy (sts:AssumeRoleWithWebIdentity)
- BLOCK: Any S3 bucket without public access block (all 4 flags = true)
- BLOCK: Any security group with ingress 0.0.0.0/0 on non-443/80 ports
- BLOCK: Missing mandatory tags (CostCentre, Environment, Owner, Project)
- BLOCK: RDS without deletion_protection in prod
- WARN: EKS nodes using t2.* or t3.* instance types (burstable not recommended)
- WARN: NAT gateway count < 3 in prod (availability risk)
- WARN: No CloudWatch alarms defined for new services
- INFO: Cost-saving opportunities (Spot, Graviton, rightsizing suggestions)

CDK DIFF OUTPUT:
{cdk_diff_output}
{synth_context}
"""

    response = client.messages.create(
        model=MODEL,
        max_tokens=2048,
        system=system_prompt,
        messages=[{"role": "user", "content": user_message}],
    )

    raw = response.content[0].text
    log.info("review_agent.response_received", job_id=job_id, verdict_preview=raw[:100])

    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        import re
        match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", raw, re.DOTALL)
        if match:
            data = json.loads(match.group(1))
        else:
            # Fallback: return WARN if parsing fails
            return ReviewResult(
                verdict="WARN",
                summary="Review agent could not parse CDK plan. Manual review required.",
                findings=[Finding(severity="WARN", rule="parse-error", resource="review-agent", detail=raw[:500])],
                cost_delta_usd_monthly=None,
                recommended_action="Manually review the CDK diff before approving.",
            )

    findings = [Finding(**f) for f in data.get("findings", [])]
    return ReviewResult(
        verdict=data["verdict"],
        summary=data["summary"],
        findings=findings,
        cost_delta_usd_monthly=data.get("cost_delta_usd_monthly"),
        recommended_action=data["recommended_action"],
    )
